networks:
  frontend:
    external: true
  app:
    driver: bridge
    internal: false

services:
  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    restart: unless-stopped
    networks:
      - app
      - frontend
    depends_on:
      - vault
    ports:
      - '8080'
    volumes:
      - ./.docker/templates:/etc/nginx/templates:ro
      - .:/app
    environment:
      NGINX_WEB_ROOT: /app/web
      NGINX_PORT: 8080
      NGINX_MAX_BODY_SIZE: 5M
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_SERVER_DOMAIN}`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=websecure"

  vault:
    image: hashicorp/vault
    restart: unless-stopped
    networks:
      - app
      - frontend
    ports:
      - "8200" # API
      - "8201" # UI
    volumes:
      - .docker/data/logs:/vault/logs/:rw
      - .docker/data/data:/vault/data/:rw
      - .docker/data/config:/vault/config/:rw
      - .docker/data/file:/vault/file/:rw
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config/config.hcl

  promtail:
    image: grafana/promtail
    command: -config.expand-env=true -config.file=/mnt/config/promtail-config.yaml
    restart: unless-stopped
    networks:
      - app
    volumes:
      - .docker/promtail-config.yaml:/mnt/config/promtail-config.yaml:ro
      - .docker/data/logs:/app/logs:ro
      - .docker/data/promtail:/data:rw
    environment:
      CLIENT_URL: "${PROMTAIL_CLIENT_URL}"
