server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /data/positions.yaml

clients:
  - url: ${CLIENT_URL}

scrape_configs:
- job_name: vault_audit_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: auditlogs
      __path__: /app/logs/audit.log
- job_name: vault_system_operational_logs
  static_configs:
  - targets:
      - localhost
    labels:
      job: systemlogs
      __path__: /app/logs/vault.log
